name: Build LaTeX document

on:
  push:

jobs:
  build_latex:
    name: Build LaTeX
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.gen_filename.outputs.filename }}
    steps:
      - 
        name: Set up Git repository
        uses: actions/checkout@v2
      - 
        name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          root_file: main.tex
          args: -pdf -bibtex --shell-escape -file-line-error -halt-on-error -interaction=nonstopmode
      - 
        id: gen_filename
        name: Generate Filename
        run: |
          reponame=$(echo "${{ github.repository }}" | sed -r 's/\//-/g')
          sha=$(printf "%.7s" "${{ github.sha }}" )
          FILENAME="${reponame}_${sha}.pdf"
          echo "filename=${FILENAME}" >> $GITHUB_ENV
          echo "filename=${FILENAME}" >> $GITHUB_OUTPUT
      - 
        name: Rename Output File
        run: mv src/index.pdf "src/${{ env.filename }}"
      - 
        uses: actions/upload-artifact@v2
        with:
          name: LaTeX to PDF
          path: "src/${{ env.filename }}"

  upload_to_release:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: build_latex
    if: ${{ github.ref_type == 'tag' }}
    steps:
      -
        name: Download build
        uses: actions/download-artifact@v3
        with:
          name: LaTeX to PDF
      - 
        name: Generate Filename
        run: |
          reponame=$(echo "${{ github.repository }}" | sed -r 's/\//-/g')
          tag=$(echo "${{ github.ref }}" | sed -r 's/refs\/tags\///g')
          echo "filename_tag=${reponame}_${tag}.pdf" >> $GITHUB_ENV
      - 
        name: Rename File
        run: mv ${{ needs.build_latex.outputs.filename }} ${{ env.filename_tag }}
      - 
        name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.filename_tag }}
          asset_name: ${{ env.filename_tag }}
          tag: ${{ github.ref }}